import aplusImg from '../components/store/img/img-aplus-1.jpg';
import barberImg from '../components/store/img/img-barbershop-1.jpg';
import kvastImg from '../components/store/img/img-kvast-1.jpg';
import mishkaImg from '../components/store/img/img-mishka-1.jpg';
import pinkImg from '../components/store/img/img-pink-1.jpg';
import sedonaImg from '../components/store/img/img-sedona-1.jpg';

export const CATALOG_GOODS = [
    {
        id: '001',
        title: 'Cайт SEDONA', 
        srcLogo: sedonaImg, 
        alt: 'Изображение главной страницы сайта Седона', 
        descName: 'SEDONA', 
        descInfo: 'Информационный сайт <br /> для туристов', 
        descAriaLabel: 'добавить в корзину создание сайта по шаблону SEDONA', 
        descPrice: 5000, 
        layout: 'Adaptive1', 
        features: ['Slider'], 
    },
    {
        id: '002',
        title: 'Cайт PINK APP', 
        srcLogo: pinkImg, 
        alt: 'Изображение главной страницы сайта PINK', 
        descName: 'PINK APP', 
        descInfo: 'Продуктовый лендинг приложения для iOS и Android', 
        descAriaLabel: 'добавить в корзину создание сайта по шаблону PINK APP', 
        descPrice: 6000, 
        layout: 'Adaptive1', 
        features: ['blockFeatures', 'Slider'], 
    },
    {
        id: '003',
        title: 'Cайт Барбершоп «Бородинский»', 
        srcLogo: barberImg, 
        alt: 'Изображение главной страницы сайта Барбершоп «Бородинский»', 
        descName: 'Barbershop', 
        descInfo: 'Сайт мужской парикмахерской', 
        descAriaLabel: 'добавить в корзину создание сайта по шаблону Барбершоп «Бородинский»', 
        descPrice: 12000, 
        layout: 'Adaptive1', 
        features: ['blockFeatures'], 
    },
    {
        id: '004',
        title: 'Cайт MISHKA', 
        srcLogo: mishkaImg, 
        alt: 'Изображение главной страницы сайта MISHKA', 
        descName: 'Mishka', 
        descInfo: 'Сайт о товарах ручной работы', 
        descAriaLabel: 'добавить в корзину создание сайта по шаблону MISHKA', 
        descPrice: 2000, 
        layout: 'Fixed2', 
        features: ['blockFeatures', 'Gallery'], 
    },
    {
        id: '005',
        title: 'Cайт A+', 
        srcLogo: aplusImg, 
        alt: 'Изображение главной страницы сайта A+', 
        descName: 'A+', 
        descInfo: 'Сайт учебного заведения', 
        descAriaLabel: 'добавить в корзину создание сайта по шаблону А+', 
        descPrice: 8000, 
        layout: 'Fixed2', 
        features: ['Slider', 'blockFeatures'], 
    },
    {
        id: '006',
        title: 'Cайт КВАСТ', 
        srcLogo: kvastImg, 
        alt: 'Изображение главной страницы сайта КВАСТ', 
        descName: 'КВАСТ', 
        descInfo: 'Сайт производителя крафтового кваса', 
        descAriaLabel: 'добавить в корзину создание сайта по шаблону КВАСТ', 
        descPrice: 7000, 
        layout: 'Fixed2', 
        features: ['blockFeatures', 'News', 'Gallery'], 
    },
    {
        id: '007',
        title: 'Cайт REDONA', 
        srcLogo: sedonaImg, 
        alt: 'Изображение главной страницы сайта REDONA', 
        descName: 'REDONA', 
        descInfo: 'Информационный сайт для туристов', 
        descAriaLabel: 'добавить в корзину создание сайта по шаблону REDONA', 
        descPrice: 7000, 
        layout: 'Rubber3', 
        features: ['Slider', 'News', 'Gallery'], 
    },
    {
        id: '008',
        title: 'Cайт SerINK', 
        srcLogo: pinkImg, 
        alt: 'Изображение главной страницы сайта SerINK', 
        descName: 'SerINK', 
        descInfo: 'Продуктовый лендинг приложения для iOS и Android', 
        descAriaLabel: 'добавить в корзину создание сайта по шаблону SerINK APP', 
        descPrice: 2000, 
        layout: 'Rubber3', 
        features: ['News', 'Gallery', 'Cart'], 
    },
    {
        id: '009',
        title: 'Cайт beauty «TuffyShop»', 
        srcLogo: barberImg, 
        alt: 'Изображение главной страницы cайта beauty «TuffyShop»', 
        descName: 'TuffyShop', 
        descInfo: 'Сайт мужской парикмахерской', 
        descAriaLabel: 'добавить в корзину создание сайта по шаблону Барбершоп «Бородинский»', 
        descPrice: 9000, 
        layout: 'Rubber3', 
        features: ['blockFeatures', 'News', 'Gallery', 'Cart'], 
    },
    {
        id: '010',
        title: 'Cайт Karatuwka', 
        srcLogo: mishkaImg, 
        alt: 'Изображение главной страницы сайта Karatuwka', 
        descName: 'Karatuwka', 
        descInfo: 'Сайт о товарах ручной работы', 
        descAriaLabel: 'добавить в корзину создание сайта по шаблону Karatuwka', 
        descPrice: 5000, 
        layout: 'Fixed2', 
        features: ['blockFeatures', 'News', 'Gallery', 'Cart'],
    },
    {
        id: '011',
        title: 'Cайт Zenda', 
        srcLogo: aplusImg, 
        alt: 'Изображение главной страницы сайта Zenda', 
        descName: 'Zenda', 
        descInfo: `Сайт учебного заведения`, 
        descAriaLabel: 'добавить в корзину создание сайта по шаблону Zenda', 
        descPrice: 10000, 
        layout: 'Rubber3', 
        features: ['Slider', 'News', 'Gallery', 'Cart'], 
    },
    {
        id: '012',
        title: 'Cайт Raketa', 
        srcLogo: kvastImg, 
        alt: 'Изображение главной страницы сайта Raketa', 
        descName: 'Raketa', 
        descInfo: `Сайт производителя крафтового Raketa`, 
        descAriaLabel: 'добавить в корзину создание сайта по шаблону Raketa', 
        descPrice: 3000, 
        layout: 'Fixed2', 
        features: ['Slider', 'News', 'Gallery', 'Cart'], 
    }, 
]
